### ISSUE TITLE
line 33 error ha instagram-py tho dhiyan sa dakho

### ISSUE THREAD

**Issue by Mr-YENOJ-alt** [noob-hackers/ighack#1]

**Comment by noob-hackers** [comment]
Please past screen shot bro

**Comment by Inderveerjoney** [comment]
bro mana script ko manally bhee try kea tho bro password nhi nikal raha only baar baar checking ho raha ha

**Comment by AmanMishra1321** [comment]
![Screenshot_2020-06-25-16-51-19-803_com termux](https://user-images.githubusercontent.com/47735794/85710665-2105c580-b704-11ea-8089-3f7e4d39c247.jpg)
it is showing like that

**Comment by mmore-hack** [comment]
Am also facing the same problem as shown in above screenshot, please help

**Comment by mmore-hack** [comment]
@noob-hackers , please help

**Comment by kayaky597** [comment]
![Screenshot_20211209-190041_Termux](https://user-images.githubusercontent.com/95892212/145499675-6f52bacf-4439-4962-8062-5b6a9f0eea3e.jpg)
