### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by brayanasf** [noob-hackers/ighack#12]
How do i start tor?
How do i install it and run it?
Basically what im asking is what do i do after installing ighack?

**Comment by agustdaegu** [comment]
```
pkg install tor
tor
```

then start a new session¹ and start the tool.

¹just swipe from left to right and a side menu will show up

![example.jpg](https://user-images.githubusercontent.com/79005205/124519968-49320500-ddeb-11eb-9b80-f40f21d88171.jpg)
