### ISSUE TITLE
detecting correct pass

### ISSUE THREAD

**Issue by MrBlack0033** [noob-hackers/ighack#21]
it seems it can't detect the right pass if the account that you are testing has 2auth active on it 
**however**
it will keep testing the same pass for like 100 times which is not right since we are using tor to change ip repeatedly so at least 1 ip have to be goof in every 20 ips so if it keep repeating the same pass its probably because account has 2 auth active but that is the right pass so....
oh one more thing 
could you modify the code to use multi thread on tor ?
'cause i used a script called Instainsane many years age but it had very good speed to test password 
you can find it in github but it won't work correctly 
thnx

**Comment by meyoui** [comment]
will instainsane work at all??

**Comment by lessa1331** [comment]
> will instainsane work at all??
> 
>
