### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by abizer94** [noob-hackers/ighack#22]
It keeps repeating the same password also how do we use the manual function I downloaded a pass list that is TXT but what is the location I put in

**Comment by agustdaegu** [comment]
I think it repeats the same password because you aren't a root user.

if you want to use a passlist that is, for example, in your downloads folder, you should write:
`/storage/emulated/0/Downloads/passlist.txt/`

**Comment by Mhmdahmad211** [comment]
https://instagram.com/aseel.privv._?utm_medium=copy_link
