### ISSUE TITLE
Ighack error

### ISSUE THREAD

**Issue by drefgol** [noob-hackers/ighack#24]
I get an error here
![Screenshot_2021-04-06-05-50-45-527_com termux](https://user-images.githubusercontent.com/80407687/113656527-5c262380-969c-11eb-844d-e2a9a4214338.jpg)

**Comment by Gulmini** [comment]
Probably the python package instagram-py is not installed
I don't exactly know if the procedure is different on your os but it should be "pip install instagram-py" or "pip3 install instagram-py"

**Comment by Rehaan760** [comment]
not working ighack

**Comment by Rehaan760** [comment]
same problem
