### ISSUE TITLE
Why are this showing all the time.![Screenshot_20210506_103722.jpg](https://user-images.githubusercontent.com/82598865/117244661-14d7b200-ae57-11eb-8463-ac36be80002b.jpg) pls help me because I already install the pkg install tor but there is only problem face

### ISSUE THREAD

**Issue by Shreyash900** [noob-hackers/ighack#26]
Why are this showing all the time.![Screenshot_20210506_103722.jpg](https://user-images.githubusercontent.com/82598865/117244661-14d7b200-ae57-11eb-8463-ac36be80002b.jpg) pls help me because I already install the pkg install tor but there is only problem face 

_Originally posted by @Shreyash900 in https://github.com/noob-hackers/ighack/issues/18#issuecomment-833228089_

**Comment by mrhormones** [comment]
Your WiFi connection isn't sufficient. You need a full 4 bars for optimal operation

**Comment by Kartik1473** [comment]
Did you activated tor ? If not activate it by writing tor simply.

**Comment by alimoh6** [comment]
same thing happens to me

**Comment by agustdaegu** [comment]
```
pkg install tor
tor
```

then open a new session¹ and start the tool.

¹just swipe from left to right and a side menu will show up

![example.jpg](https://user-images.githubusercontent.com/79005205/124519870-f22c3000-ddea-11eb-9b0d-86e10ad388e3.jpg)

**Comment by Poiuytrewqa123456789** [comment]
Hi

**Comment by Poiuytrewqa123456789** [comment]
https://instagram.com/21_aha?utm_medium=copy_link
