### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YanielCast** [noob-hackers/ighack#29]
I'm testing this app and it's not working⚠️
WHAT IS "IMSTAGRAM-PY" ? ⚠️
Manual attack doesn't work either⚠️
Don't understend ⚠️
My ig: @yanielcast

![Screenshot_20210523-132921](https://user-images.githubusercontent.com/79879935/119272418-57291f00-bbcb-11eb-8f52-be0795036ac7.jpg)

**Comment by agustdaegu** [comment]
try with:
`pip install instagram-py`

**Comment by ibrahim-hacker** [comment]
![Uploading IMG_20211127_114353.jpg…]()
Not working !!
