### ISSUE TITLE
Tor configuration invalid or server down

### ISSUE THREAD

**Issue by akshaysmarty00786** [noob-hackers/ighack#3]

**Comment by RIKAZE-x-code** [comment]
Same

**Comment by AmanMishra1321** [comment]
**same here**

**Comment by nsshafi** [comment]
Same problm any solution

**Comment by shubhman06** [comment]
Mine too

**Comment by agustdaegu** [comment]
```
pkg install tor
tor
```

then start a new session¹ and start the tool.

¹just swipe from left to right and a side menu will show up

![example.jpg](https://user-images.githubusercontent.com/79005205/124520068-93b38180-ddeb-11eb-9b65-260c63e963df.jpg)
