### ISSUE TITLE
Unable to locate pkg tor

### ISSUE THREAD

**Issue by AhmedAAK313** [noob-hackers/ighack#30]
Hello I typed pkg install tor and it says Unable to locate pkg tor
Them I typed apt install tor and again Unable to locate pkg tor
pkg up -y
apt-get update
And still my problem not solved
Please anyone can help?

**Comment by agustdaegu** [comment]
if you downloaded Termux from the PlayStore please delete it from your phone and download the latest version from its official website https://termux.com/
