### ISSUE TITLE
Error no 111

### ISSUE THREAD

**Issue by Jesudasva** [noob-hackers/ighack#52]
After connecting to tor network still not able to establish connection always returned with error code 111. See my attachments
![Screenshot_20220221-230046_Termux (1)](https://user-images.githubusercontent.com/93055252/155004121-1eedbd40-1326-4f03-b25c-da08ec442282.jpg)
![Screenshot_20220221-230221_Pixelcam_Dise_Clone](https://user-images.githubusercontent.com/93055252/155004136-18180705-d334-4ad3-a9b7-f0a0cb6bdc09.png)

**Comment by Abuegisar** [comment]
I also have the same problem please, how I can solve it
